version: "3.2"

services:
  phpunit_wp:
    build:
      context: .docker
      dockerfile: Dockerfile.phpunit
    volumes:
      - "./public_html/wp-content:/app/public_html/wp-content"
      - "./phpunit.xml.dist:/app/phpunit.xml.dist"
      - "./phpunit-bootstrap.php:/app/phpunit-bootstrap.php"
      - "./phpunit-database-testcase.php:/app/phpunit-database-testcase.php"
      - "./.docker/bin:/var/scripts"
      - "./.docker/test_suite:/tmp/wp"
    stdin_open: true
    depends_on:
      - "phpunit_db"
  phpunit_db:
    image: "mariadb:12.0"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: "wordpress_test"
    volumes:
     - testsuite-db:/var/lib/mysql/

volumes:
  testsuite: {}
  testsuite-db: {}
